version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=tracker
      - MYSQL_PASSWORD=tracker
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
